function [nx,T2,SPE]=PCA_detection(x,y,P,LATENT,A)
[mx,nx]=size(x);
% [my,ny]=size(y);
%求均值
% y_mean=mean(y,2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
x = transpose(x);
%%进行数据过程监测
SPE=zeros(nx,1);
T2=zeros(nx,1);
for i=1:nx
    T2(i) = x(i,:)*P(:,1:A)*inv(diag(LATENT(1:A)))*P(:,1:A)'*x(i,:)';
    SPE(i)=x(i,:)*(eye(mx) - P(:,1:A)*P(:,1:A)')*x(i,:)';
end
end